# Generated by Django 4.2.15 on 2024-08-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avt_url',
            field=models.ImageField(blank=True, upload_to='user_avt/'),
        ),
    ]
