# Generated by Django 4.2.7 on 2023-12-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avt_url',
            field=models.CharField(default='images/avatar.png', max_length=100),
        ),
    ]
