# Generated by Django 4.2.7 on 2023-12-02 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_total_duration_alter_category_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='total_duration',
        ),
    ]
